name: Selenium Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      app:
        image: php:8.2-apache
        ports:
          - 8080:80
        volumes:
          - ./:/var/www/html
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run tests
        run: |
          npm install
          TEST_URL=http://app:8080 npm test