name: Selenium Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          google-chrome --version

      - name: Install NPM Dependencies
        run: npm install

      - name: Start PHP Server
        run: |
          php -S localhost:8080 &> php-server.log &
          sleep 5  # Wait for server to boot

      - name: Run Tests
        run: npm test
